In [1]:
import os, re
import pandas as pd

os.chdir('/GPUFS/sysu_jhluo_1/wangyh/project/BLCA_TMB/processing/mil classifier/')

In [2]:
def metrics_recording(description):
    with open(f'{description}/metrics.log') as f:

#     pattern = re.compile(r'lr:(.+),weight:([\d\.]+),fold:(\d+),metric:(\w+),avg_score: ([\d\.]+),auc for TMB-H: ([\d\.]+),f1:([\d\.]+),tn_fp_fn_tp:\((\d+), (\d+), (\d+), (\d+)\)')
        pattern = re.compile(r'lr:(.+),weight:(.+),fold:(.+),metric:(.+),avg_score: (.+),auc for TMB-H: ([\d\.]+),f1:([\d\.]+),tn_fp_fn_tp:\((\d+), (\d+), (\d+), (\d+)\)')
        log = f.read()
        data = []
        for line in log.split('\n'):
            match = pattern.search(line)
    #         print(match.group(9))
            if match:
                data.append([float(match.group(1)), float(match.group(2)), int(match.group(3)), match.group(4), 
                            float(match.group(5)), float(match.group(6)), float(match.group(7)), 
                            int(match.group(8)), int(match.group(9)), int(match.group(10)), int(match.group(11))])

        df = pd.DataFrame(data, columns=['lr', 'weight', 'fold', 'metric', 'avg_score', 'auc', 'f1', 'tn', 'fp', 'fn', 'tp'])
        return df
    
def show_topK_metrics(df,k,metrics):
    top_idx = df.sort_values(f'{metrics}', ascending=False).head(k).index
    result = df.loc[top_idx,:]
    print(df[f'{metrics}'].describe())
    return result

In [10]:
df = metrics_recording('3fold_2')

df = df[~df.duplicated()]

df

,lr,weight,fold,metric,avg_score,auc,f1,tn,fp,fn,tp
0,0.000675,0.000062,0,best_loss,0.136986,0.410256,0.390244,40,20,5,8
1,0.000675,0.000062,0,best_score,0.328767,0.441026,0.350000,40,20,6,7
2,0.000675,0.000062,0,best_auc,0.136986,0.410256,0.390244,40,20,5,8
3,0.000002,0.000004,0,best_loss,0.178082,0.330769,0.333333,28,32,4,9
4,0.000002,0.000004,0,best_score,0.123288,0.326923,0.327273,27,33,4,9
...,...,...,...,...,...,...,...,...,...,...,...
4029,0.000123,0.000083,2,best_score,0.438356,0.626923,0.410256,42,18,5,8
4030,0.000123,0.000083,2,best_auc,0.438356,0.626923,0.410256,42,18,5,8
4031,0.000030,0.000060,2,best_loss,0.726027,0.644872,0.428571,51,9,7,6
4032,0.000030,0.000060,2,best_score,0.712329,0.644872,0.428571,51,9,7,6
4033,0.000030,0.000060,2,best_auc,0.726027,0.647436,0.428571,51,9,7,6

In [11]:
show_topK_metrics(df,10,'auc')

count    4034.000000
mean        0.542261
std         0.134649
min         0.325641
25%         0.403846
50%         0.580769
75%         0.653846
max         0.826923
Name: auc, dtype: float64

,lr,weight,fold,metric,avg_score,auc,f1,tn,fp,fn,tp
1952,0.000675,0.000044,1,best_score,0.698630,0.826923,0.642857,54,6,4,9
2066,0.000480,0.000058,1,best_auc,0.671233,0.817949,0.625000,51,9,3,10
2065,0.000480,0.000058,1,best_score,0.671233,0.817949,0.625000,51,9,3,10
2506,0.000763,0.000085,1,best_loss,0.753425,0.810256,0.588235,49,11,3,10
2507,0.000763,0.000085,1,best_score,0.753425,0.810256,0.588235,49,11,3,10
2508,0.000763,0.000085,1,best_auc,0.753425,0.810256,0.588235,49,11,3,10
1742,0.000709,0.000088,0,best_auc,0.739726,0.805128,0.642857,54,6,4,9
1953,0.000675,0.000044,1,best_auc,0.643836,0.803846,0.580645,51,9,4,9
1951,0.000675,0.000044,1,best_loss,0.643836,0.803846,0.580645,51,9,4,9
1429,0.000480,0.000044,0,best_score,0.684932,0.798718,0.514286,47,13,4,9

In [11]:
show_topK_metrics(df,10,'f1')

count    600.000000
mean       0.174762
std        0.147903
min        0.000000
25%        0.000000
50%        0.190476
75%        0.311688
max        0.594595
Name: f1, dtype: float64

,lr,weight,fold,metric,avg_score,auc,f1,tn,fp,fn,tp
297,0.000348,0.000008,0,best_score,0.657534,0.828205,0.594595,47,13,2,11
241,0.000348,0.000002,0,best_score,0.684932,0.833333,0.594595,47,13,2,11
157,0.000348,0.000063,0,best_score,0.657534,0.785897,0.580645,51,9,4,9
389,0.000348,0.000083,0,best_score,0.671233,0.771795,0.580645,51,9,4,9
341,0.000348,0.000059,0,best_score,0.643836,0.787179,0.580645,51,9,4,9
105,0.000348,0.000004,0,best_score,0.561644,0.830769,0.564103,45,15,2,11
149,0.000348,0.000010,0,best_score,0.575342,0.825641,0.564103,45,15,2,11
129,0.000348,0.000011,0,best_score,0.575342,0.821795,0.564103,45,15,2,11
189,0.000348,0.000030,0,best_score,0.520548,0.817949,0.536585,43,17,2,11
97,0.000123,0.000083,0,best_score,0.630137,0.735897,0.514286,47,13,4,9